config/routes.rb
Rails.application.routes.draw do
  get 'order/new'
  get 'welcome/works'


  post '/welcome/create'
  post 'to_do_task/submitCheckboxVal'
  post 'to_do_task/destroybyajax'  => 'to_do_task#destroybyajax'

  post 'to_do_task/refreshMonthView' => 'to_do_task#refreshMonthView'
  post 'to_do_task/refreshDayView' => 'to_do_task#refreshDayView'

  devise_for :users, controllers: { registrations: 'users/registrations',sessions: 'users/sessions' }

  devise_scope :user do
    get 'users/sign_out' => 'devise/sessions#destroy'
  end

  resources :users do
    resources :order
    get 'to_do_task/displayMonthView' => 'to_do_task#displayMonthView'
    get 'to_do_task/displayDayView' => 'to_do_task#displayDayView'
    get 'to_do_task/todowithreact' => 'to_do_task#todowithreact'

    post 'to_do_task/new' => 'to_do_task#create'
    resources :to_do_task
    get 'order/listallOrders'
  end



  root 'welcome#welcome'

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
end

app/controllers/order_controller.rb
class OrderController < ApplicationController
  def new

    @user = User.find(params[:user_id])

  end

  def index
  end

  def create
    p params
    @user = User.find(params[:user_id])
    @order = @user.orders.create(order_params)
    @order.save
    redirect_to user_order_index_path
  end
  def update

  end

  def show
    @user = User.find(params[:user_id])
    @order = @user.orders
    p @order
  end

  private
  def order_params
    params.require(:order).permit(:field1, :field2)
  end
end

app/helpers/order_helper.rb
module OrderHelper
end

app/views/order/index.html.erb
<div>
  <%= link_to "create order", :controller => "order", :action => "new", :type => '5', :html => { :class => "btn" } %>
</div>
<div>
  <%= link_to "list orders", user_order_listallOrders_path%>
</div>


<div>
  <%= link_to "ToDOTask", user_to_do_task_index_path%>
</div>

<div>
  <%= link_to "TO DO WIth REACT", user_to_do_task_todowithreact_path%>
</div>

app/views/order/new.html.erb
    <%= form_for(@user.orders.build, as: @user.orders.build, :url => { :controller => "order", :action => "create" }) do |form| %>
  <p>
    <%= form.label :field1 %><br>
    <%= form.text_field :field1 %>
  </p>
  <p>
    <%= form.label :field2 %><br>
    <%= form.text_area :field2 %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/order/show.html.erb
<table>
  <tr>
    <th>field 1</th>
    <th>field 2</th>

  </tr>

  <% @order.each do |order| %>
    <tr>
      <td style="padding:2Px;"><%= order.field1 %></td>
      <td style="padding:2Px;"><%= order.field2 %></td>

    </tr>
  <% end %>
</table>