config/routes.rb
Rails.application.routes.draw do
  get 'order/new'
  get 'welcome/works'


  post '/welcome/create'
  post 'to_do_task/submitCheckboxVal'
  post 'to_do_task/destroybyajax'  => 'to_do_task#destroybyajax'

  post 'to_do_task/refreshMonthView' => 'to_do_task#refreshMonthView'
  post 'to_do_task/refreshDayView' => 'to_do_task#refreshDayView'

  devise_for :users, controllers: { registrations: 'users/registrations',sessions: 'users/sessions' }

  devise_scope :user do
    get 'users/sign_out' => 'devise/sessions#destroy'
  end

  resources :users do
    resources :order
    get 'to_do_task/displayMonthView' => 'to_do_task#displayMonthView'
    get 'to_do_task/displayDayView' => 'to_do_task#displayDayView'
    get 'to_do_task/todowithreact' => 'to_do_task#todowithreact'

    post 'to_do_task/new' => 'to_do_task#create'
    resources :to_do_task
    get 'order/listallOrders'
  end



  root 'welcome#welcome'

end

app/models/to_do_task.rb
class ToDoTask < ActiveRecord::Base
  belongs_to :User
  validates :taskToDO,:date, presence: true
  # validates :date, presence: true,
  # validate do |ToDoTask|
  #   ToDoTask.errors.add_to_base("Task can not be blank") if ToDoTask.taskToDO.blank?
  #   ToDoTask.errors.add_to_base("date can not be blank") if ToDoTask.date.blank?
  #
  # end
end

app/helpers/to_do_task_helper.rb
module ToDoTaskHelper
end

app/views/to_do_task/_formForAllTask.html.erb
<%if @AllTasks.empty? %>
  <p style="color: blueviolet;font-weight: bold;font size:50px;text-align: center;margin-top: 3%;"><%=@msgForNOTODO%> </p>
<%else%>
  <%if @allTaskView != "monthView"%>
      <% @AllTasks.each do |task| %>
        <%next if task.id== nil%>
        <%if @allTaskView == "AllView"%>
          <div class="taskDisplay">
        <%else%>
          <div class="taskDisplay" style="margin:0 35%;">
      <% end%>
            <span style="width:5%;"> <input  id='task_<%=task.id%>' name='<%=task.id%>' type="checkbox" value='<%=task.status%>' class="doneCheck" /></span>
            <span style="width:40%;"><%= task.taskToDO %></span>
            <%if @allTaskView == "AllView"%>
              <span style="width:30%;">Date:<%= task.date.strftime("%d/%m/%Y")  %></span>
           <%end%>
            <span style="width:5%;"><%= link_to image_tag("delete.png"), user_to_do_task_path(@user, task), title: 'Delete Task', data: {:confirm => 'Are you sure?'}, :method => :delete %></span>
          </div>
      <%end%>
  <%elsif @monthView != nil%>
    <%@monthView.each do|key,list|%>
      <h4 style="color:coral;text-align: center;" ><%= key%></h4>
        <%list.each do |task|%>
          <%next if task.id== nil%>
          <div class="taskDisplay" style="margin:0 35%;">
            <span style="width:5%;"><input  id='task_<%=task.id%>' name='<%=task.id%>' type="checkbox" value='<%=task.status%>' class="doneCheck" /></span>
            <span style="width:40%;"><%= task.taskToDO.to_s %></span>
            <span style="width:5%;"><%= link_to image_tag("delete.png"), user_to_do_task_path(@user, task), title: 'Delete Task', data: {:confirm => 'Are you sure?'}, :method => :delete %></span>
          </div>
        <%end%>
    <%end%>
  <%end%>
<%end%>

app/views/to_do_task/displayDayView.html.erb
<div id="addToDoTask" >
  <%= link_to 'Back', user_to_do_task_index_path %>

  <p style="color: white;font-weight: bold;font size:50px;text-align: center;">TODO Day View</p>

  <div style="margin:0 32%">
    <span ><%= image_tag("next.png" , class: "oneDayBack")%></span>
    <span><input type="text" name="selected[date]" id="selectedDay" data-id='<%= @user.id%>' data-placeholder="Date of birth" value="<%= @date%>"></span>
    <span><%= image_tag("next.png", class: "oneDayFwd") %></span>
  </div>

  <div id="displayDailytasks"  style="margin-top: 3%;">
  </div>
</div>

<script>

    $( function() {
        $( "#selectedDay" ).datepicker();
    } );

    ////day view
    $('.oneDayBack').on("click", function () {
        getDayToDisplay("oneDayBack");
    });

    $('.oneDayFwd').on("click", function () {
        getDayToDisplay("oneDayFwd");
    });
    getDayToDisplay("onLoad");

    $("#selectedDay").change(function() {
        getDayToDisplay("onLoad");
    });

    function getDayToDisplay(type) {
        var myVariable = $('#selectedDay').val();
        // var myVariable = "jan 2014"
        var makeDate = new Date(myVariable);
        if (type == "oneDayBack"){
            makeDate = new Date(makeDate.setDate(makeDate.getDate() - 1));}
        else if(type == "oneDayFwd"){
            makeDate = new Date(makeDate.setDate(makeDate.getDate() + 1));}
        else if(type == "onLoad"){
            makeDate = new Date(makeDate.setDate(makeDate.getDate() ));}

        var dateToSend =(makeDate.getMonth() + 1) + "/" + makeDate.getDate() + "/" + makeDate.getFullYear()

        $('#selectedDay').val(dateToSend);

        var userId = $('#selectedDay').attr('data-id');
        $.ajax({
            url: '/to_do_task/refreshDayView',
            type: 'post',
            data: {'selectedDay' :dateToSend,'user_id' : userId },
            success: function( data ){
                $("#displayDailytasks").html(" ").html(data);
                eachDoncheck();

            }
        });
    }
</script>

app/views/to_do_task/displayMonthView.html.erb
<div id="addToDoTask" >
  <%= link_to 'Back', user_to_do_task_index_path %>

  <p style="color: white;font-weight: bold;font size:50px;text-align: center;">TODO Month</p>

  <div style="margin:0 32%">
    <span><%= image_tag("next.png" , class: "oneMonthBack")%></span>
    <span><input type="text" name="selected[date]" id="selectedMonth" data-id='<%= @user.id%>'  value="<%=@day%>"></span>
    <span><%= image_tag("next.png", class: "oneMonthFwd") %></span>
  </div>

  <div id="displayMonthtasks"  style="margin-top: 3%;">
  </div>
</div>

<script>
    //MonthView

    $('.oneMonthBack').on("click", function () {
        getMonthToDisplay("oneMonthBack");
    });

    $('.oneMonthFwd').on("click", function () {
        getMonthToDisplay("oneMonthFwd");
    });
    getMonthToDisplay("onLoad");

    function getMonthToDisplay(type){
        var myVariable = $('#selectedMonth').val();
        // var myVariable = "jan 2014"
        var makeDate = new Date(myVariable);
        if (type == "oneMonthBack"){
            makeDate = new Date(makeDate.setMonth(makeDate.getMonth() - 1));}
        else if(type == "oneMonthFwd"){
            makeDate = new Date(makeDate.setMonth(makeDate.getMonth() + 1));}
        else if(type == "onLoad"){
            makeDate = new Date(makeDate.setMonth(makeDate.getMonth() ));}


        var dateTosend = ('0' + (makeDate.getMonth()+1)).slice(-2).toString() +" "+ makeDate.getFullYear().toString();
        $('#selectedMonth').val(monthNames[makeDate.getMonth() ]+" "+ makeDate.getFullYear());
        callAjax(dateTosend);

    }

    function callAjax(dateTosend) {
        var selectedMonth = dateTosend
        var userId =$("#selectedMonth").attr('data-id');

        $.ajax({
            url: '/to_do_task/refreshMonthView',
            type: 'post',
            data: {'selectedMonth': selectedMonth,'user_id': userId },
            success: function( data ){
                $("#displayMonthtasks").html(" ").html(data);
                eachDoncheck();
            }
        });

    }
</script>

app/views/to_do_task/index.html.erb
<div class="showAllToDoTask" >
  <%= link_to "TODO Day View", user_to_do_task_displayDayView_path %>
</div>
<div class="showAllToDoTask" >
  <%= link_to "TODO Month ", user_to_do_task_displayMonthView_path%>
</div>

<div class="showAllToDoTask" >
  <%= link_to "new task ", new_user_to_do_task_path%>
</div>

<div class="showAllToDoTask">
  <p style="color: white;font-weight: bold;font size:50px;text-align: center;">All TODO Tasks</p>
  <%= render 'to_do_task/formForAllTask' %>
</div>

app/views/to_do_task/new.html.erb
  <div id="addToDoTask" >
  <p style="color: white;font-weight: bold;font size:50px;text-align: center;">Add new Task</p>
    <%= form_for(@user.to_do_tasks.build, as: @user.to_do_tasks.build, :url => { :controller => "to_do_task", :action => "create" }) do |form| %>

      <div style="width:70%;margin:0 15%;">
        <span><%= form.text_field :taskToDO ,placeholder:"What needs to be done?"%></span>
        <!--<span><%#= form.date_field :date%></span>-->
        <span><%= form.text_field :date, placeholder:"Select date" %></span>

        <span><%= form.submit "Add Task"%></span>
      </div>

      <% if @toDoTask && @toDoTask.errors.any? %>
        <% @toDoTask.errors.full_messages.each do |msg| %>
          <p style="color: red;font-weight: bold;font size:50px;text-align: center;"><%= msg %></p>
        <% end %>
      <% end %>
    <% end %>
  </div>

app/views/to_do_task/todowithreact.html.erb
<%= react_component('Main', userid: params[:user_id])%>